name: Flutter CI web

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
    - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Setup Java environment
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Setup the flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      
      # Get flutter dependencies
      - run: flutter pub get
      
      # Check for any formatting issues in the code
      - run: dart format --set-exit-if-changed . || true

      # Build web version
      - run: flutter build web --release

      # Upload web build to the artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  deploy-web:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Web Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: ./web-deploy

      - name: Upload Web to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: "./web-deploy/"
          server-dir: "/public_html/api.made-by-free.com/mcheads/web/"
